// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Opdracht;

namespace Opdracht.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20201122125335_Laatste")]
    partial class Laatste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Opdracht.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Straat")
                        .HasColumnType("TEXT")
                        .HasColumnName("Straatnaam");

                    b.HasKey("Id");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("Opdracht.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtikelNaam")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestelling");
                });

            modelBuilder.Entity("Opdracht.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .HasColumnType("TEXT");

                    b.Property<int>("AdresId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdresId")
                        .IsUnique();

                    b.ToTable("KlantTabel");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Klant");
                });

            modelBuilder.Entity("Opdracht.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Opdracht.ProductKlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("ProductId1");

                    b.ToTable("ProductKlant");
                });

            modelBuilder.Entity("Opdracht.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommenterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("MakerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("ReviewId");

                    b.HasIndex("CommenterId");

                    b.HasIndex("MakerId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Opdracht.PremiumKlant", b =>
                {
                    b.HasBaseType("Opdracht.Klant");

                    b.Property<int>("KortingCode")
                        .HasColumnType("INTEGER");

                    b.ToTable("KlantTabel");

                    b.HasDiscriminator().HasValue("PremiumKlant");
                });

            modelBuilder.Entity("Opdracht.Bestelling", b =>
                {
                    b.HasOne("Opdracht.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("Opdracht.Klant", b =>
                {
                    b.HasOne("Opdracht.Adres", "Adres")
                        .WithOne("Klant")
                        .HasForeignKey("Opdracht.Klant", "AdresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("Opdracht.ProductKlant", b =>
                {
                    b.HasOne("Opdracht.Klant", "Klant")
                        .WithMany("ProductKlant")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opdracht.Product", "Product")
                        .WithMany("ProductKlant")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Klant");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Opdracht.Review", b =>
                {
                    b.HasOne("Opdracht.Klant", "Commenter")
                        .WithMany("ReviewComments")
                        .HasForeignKey("CommenterId");

                    b.HasOne("Opdracht.Klant", "Maker")
                        .WithMany("GemaakteReviews")
                        .HasForeignKey("MakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commenter");

                    b.Navigation("Maker");
                });

            modelBuilder.Entity("Opdracht.Adres", b =>
                {
                    b.Navigation("Klant");
                });

            modelBuilder.Entity("Opdracht.Klant", b =>
                {
                    b.Navigation("Bestellingen");

                    b.Navigation("GemaakteReviews");

                    b.Navigation("ProductKlant");

                    b.Navigation("ReviewComments");
                });

            modelBuilder.Entity("Opdracht.Product", b =>
                {
                    b.Navigation("ProductKlant");
                });
#pragma warning restore 612, 618
        }
    }
}
