// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Opdracht;

namespace Opdracht.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Opdracht.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Straat")
                        .HasColumnType("TEXT")
                        .HasColumnName("Straatnaam");

                    b.HasKey("Id");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("Opdracht.Bestelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtikelNaam")
                        .HasColumnType("TEXT");

                    b.Property<int>("KlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.ToTable("Bestelling");
                });

            modelBuilder.Entity("Opdracht.Klant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .HasColumnType("TEXT");

                    b.Property<int>("AdresId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdresId")
                        .IsUnique();

                    b.ToTable("KlantTabel");
                });

            modelBuilder.Entity("Opdracht.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Opdracht.ProductKlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlantId");

                    b.HasIndex("ProductId1");

                    b.ToTable("ProductKlant");
                });

            modelBuilder.Entity("Opdracht.Bestelling", b =>
                {
                    b.HasOne("Opdracht.Klant", "Klant")
                        .WithMany("Bestellingen")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klant");
                });

            modelBuilder.Entity("Opdracht.Klant", b =>
                {
                    b.HasOne("Opdracht.Adres", "Adres")
                        .WithOne("Klant")
                        .HasForeignKey("Opdracht.Klant", "AdresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");
                });

            modelBuilder.Entity("Opdracht.ProductKlant", b =>
                {
                    b.HasOne("Opdracht.Klant", "Klant")
                        .WithMany("ProductKlant")
                        .HasForeignKey("KlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opdracht.Product", "Product")
                        .WithMany("ProductKlant")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Klant");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Opdracht.Adres", b =>
                {
                    b.Navigation("Klant");
                });

            modelBuilder.Entity("Opdracht.Klant", b =>
                {
                    b.Navigation("Bestellingen");

                    b.Navigation("ProductKlant");
                });

            modelBuilder.Entity("Opdracht.Product", b =>
                {
                    b.Navigation("ProductKlant");
                });
#pragma warning restore 612, 618
        }
    }
}
